#ALL KEYS IN THIS FILE IS USED FOR TEST!!
networks:
  health-app:
    driver: bridge

volumes:
#  pg_data:
  es_data:
  redis_data:
#  kafka_data:
#  kong_data:

services:
  # ------------------ RAILS APP (WEB) ------------------
  web:
    image: longvulinhhoang/spree-v2-backend:latest
    container_name: spree_backend
    depends_on:
      - redis
      - elasticsearch
    environment:
      RAILS_ENV: production
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: longdz2004
      POSTGRES_HOST: spree-database.cdgsoesqu0gs.ap-southeast-2.rds.amazonaws.com
      POSTGRES_PORT: 5432
      DATABASE_URL: postgres://postgres:longdz2004@spree-database.cdgsoesqu0gs.ap-southeast-2.rds.amazonaws.com:5432/spree_v2_development #TEMP KEY FOR FAST TESTING
      REDIS_URL: redis://redis:6379/0
      ELASTICSEARCH_URL: http://elasticsearch:9200
      SECRET_KEY_BASE: 515811e5dc8f9ced57b930c3b6351483a83a63b51830863601c5a4f44850ab2d961917bdc689acea1bb79b78ec67eed838b138c89026e8f1f279347ce16a98a1 #TEMP KEY FOR FAST TESTING
      GMAIL_APP_PASSWORD: kbkw whpi wzdm lfhx  
      GMAIL_USERNAME: longprovip2508@gmail.com
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      AWS_BUCKET:
      AWS_REGION: ap-southeast-2
      STRIPE_WEBHOOK_SECRET: whsec_33a0f2920308abd6385fb17c09468ee17df15a8bfae21634e982a91d0fa3d117 #just for fast testing 
      STRIPE_PUBLISHABLE_KEY: pk_test_51S3qvy0i5JbSc9y5ne7KVBKrTcbKrcBWjXfJFOnGhBhZQmloLtbkxT1qv3z2DqPufFORnm6Z9UmmfSYoj1IuGPrD00LS9UKz2A  #TEMP KEY FOR FAST TESTING
      STRIPE_SECRET_KEY: sk_test_51S3qvy0i5JbSc9y5wAEyCn7wOv8rUtEnScgVho0qA9iQlRTWQikTA6Uy6G07t5wr60FyGMOWzmHJ1yknjiCuGV780039UPj0Q9 #TEMP KEY FOR FAST TESTING
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - health-app

  sidekiq:
    image: longvulinhhoang/spree-v2-backend:latest
    container_name: spree_sidekiq
    depends_on:
      - web
      - redis
    command: bundle exec sidekiq -C config/sidekiq.yml
    environment:
      RAILS_ENV: production
      DATABASE_URL: postgres://postgres:longdz2004@spree-database.cdgsoesqu0gs.ap-southeast-2.rds.amazonaws.com:5432/spree_v2_development #TEMP KEY FOR FAST TESTING
      REDIS_URL: redis://redis:6379/0
    networks:
      - health-app
    restart: unless-stopped
  # ------------------ REDIS ------------------
  redis:
    image: redis:latest
    container_name: my_redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - health-app

  # ------------------ ELASTICSEARCH ------------------
  elasticsearch:
    image: elasticsearch:9.1.0
    container_name: my_elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: unless-stopped
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - health-app

  # ------------------ KIBANA ------------------
  #  kibana:
  #    image: docker.elastic.co/kibana/kibana:9.1.0
  #    container_name: my_kibana
  #    depends_on:
  #      - elasticsearch
  #    environment:
  #      - ELASTICSEARCH_HOSTS=http://my_elasticsearch:9200
  #    ports:
  #      - "5601:5601"
  #    restart: unless-stopped
  #    networks:
  #      - health-app

  # ------------------ MAIN POSTGRES (FOR APP) ------------------
#  db:
#    image: postgres:15
#    container_name: my_postgres_15
#    restart: unless-stopped
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: secret
#      POSTGRES_DB: spree_v2_development
#    ports:
#      - "5432:5432"
#    volumes:
#      - pg_data:/var/lib/postgresql/data
#    networks:
#      - health-app

  # ------------------ ZOOKEEPER ------------------
  #  zookeeper:
  #    image: confluentinc/cp-zookeeper:7.4.0
  #    container_name: zookeeper
  #    environment:
  #      ZOOKEEPER_CLIENT_PORT: 2181
  #      ZOOKEEPER_TICK_TIME: 2000
  #    ports:
  #      - "2181:2181"
  #    networks:
  #      - health-app

  # ------------------ KAFKA ------------------
  #  kafka:
  #    image: confluentinc/cp-kafka:7.4.0
  #    container_name: kafka
  #    depends_on:
  #      - zookeeper
  #    environment:
  #      KAFKA_BROKER_ID: 1
  #      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
  #      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
  #      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  #      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
  #      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
  #      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
  #    ports:
  #      - "9092:9092"
  #    volumes:
  #      - kafka_data:/var/lib/kafka/data
  #    networks:
  #      - health-app
  #    restart: unless-stopped
  #
  #  # ------------------ KONG POSTGRES ------------------
  #  kong-db:
  #    image: postgres:15
  #    container_name: kong_postgres
  #    restart: unless-stopped
  #    environment:
  #      POSTGRES_USER: kong
  #      POSTGRES_PASSWORD: kongpass
  #      POSTGRES_DB: kong_database
  #    volumes:
  #      - kong_data:/var/lib/postgresql/data
  #    networks:
  #      - health-app
  #
  #  # ------------------ KONG MIGRATIONS ------------------
  #  kong-migrations:
  #    image: kong:3.5
  #    command: kong migrations bootstrap
  #    depends_on:
  #      - kong-db
  #    environment:
  #      KONG_DATABASE: postgres
  #      KONG_PG_HOST: kong-db
  #      KONG_PG_USER: kong
  #      KONG_PG_PASSWORD: kongpass
  #      KONG_PG_DATABASE: kong_database
  #    networks:
  #      - health-app
  #
  #  # ------------------ KONG GATEWAY ------------------
  #  kong:
  #    image: kong:3.5
  #    container_name: kong
  #    volumes:
  #      - ./kong.yml:/usr/local/kong/declarative/kong.yml
  #    environment:
  #      KONG_DATABASE: "off"
  #      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
  #      KONG_PROXY_ACCESS_LOG: /dev/stdout
  #      KONG_ADMIN_ACCESS_LOG: /dev/stdout
  #      KONG_PROXY_ERROR_LOG: /dev/stderr
  #      KONG_ADMIN_ERROR_LOG: /dev/stderr
  #      KONG_ADMIN_LISTEN: 0.0.0.0:8001
  #    ports:
  #      - "8000:8000" # Proxy
  #      - "8443:8443" # Proxy SSL
  #      - "8001:8001" # Admin API
  #    networks:
  #      - health-app
  #    restart: unless-stopped
  #    extra_hosts:
  #      - "host.docker.internal:172.17.0.1"
