default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV["RAILS_MAX_THREADS"] || 5 %>
  username: postgres
  password: secret
  host: 127.0.0.1
  port: 5433

development:
  <<: *default
  database: spree_v2_development

test:
  <<: *default
  database: spree_v2_test

production:
  primary:
    <<: *default
    database: spree_v2_production
  cache:
    <<: *default
    database: spree_v2_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: spree_v2_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: spree_v2_cable
    migrations_paths: db/cable_migrate
